<?php

/**
 * @file
 * Comscore module.
 */

use Drupal\comscore\InlineScript;
use Drupal\Core\Url;

/**
 * Implements hook_page_attachments().
 */
function comscore_page_attachments(array &$attachments) {
  $current_url = Url::fromRoute('<current>')->toString(TRUE)->getGeneratedUrl();
  $script = (new InlineScript())->render($current_url);
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'script',
      '#value' => $script,
    ],
    'comscore_tracking_script',
  ];
}
