comscore_direct.settings:
  type: config_object
  label: 'Node settings'
  mapping:
    site_id:
      type: numeric
    genre:
      type: string
    package:
      type: string
    clientseg:
      type: string
